# in dev environment enable the TPM2 emulator and TPM2 EK HTTP test endpoint
# for the salt-master to authenticate the dev minion
[Unit]
Wants=tpm2-emu.service tpm2-ek-http.service

[Service]
# direct tpm2-tools to use the emulator instead of the real TPM
Environment="TPM2TOOLS_TCTI=mssim:host=localhost,port=2321"
