#!/usr/bin/env python3
"""
Directly call a salt command in the modules, does not require a running salt
minion to run.
"""

from salt.scripts import salt_call

if __name__ == "__main__":
    import resource
    resource.setrlimit(resource.RLIMIT_NOFILE, (8192, 8192))
    salt_call()
